package go_linux_sensors

/*
#include "bridge.h"
#cgo LDFLAGS: -lsensors
*/
import "C"

const (
	FeatureIn         = FeatureType(C.SENSORS_FEATURE_IN)
	FeatureFan        = FeatureType(C.SENSORS_FEATURE_FAN)
	FeatureTemp       = FeatureType(C.SENSORS_FEATURE_TEMP)
	FeaturePower      = FeatureType(C.SENSORS_FEATURE_POWER)
	FeatureEnergy     = FeatureType(C.SENSORS_FEATURE_ENERGY)
	FeatureCurr       = FeatureType(C.SENSORS_FEATURE_CURR)
	FeatureHumidity   = FeatureType(C.SENSORS_FEATURE_HUMIDITY)
	FeatureMaxMain    = FeatureType(C.SENSORS_FEATURE_MAX_MAIN)
	FeatureVid        = FeatureType(C.SENSORS_FEATURE_VID)
	FeatureIntrusion  = FeatureType(C.SENSORS_FEATURE_INTRUSION)
	FeatureMaxOther   = FeatureType(C.SENSORS_FEATURE_MAX_OTHER)
	FeatureBeepEnable = FeatureType(C.SENSORS_FEATURE_BEEP_ENABLE)
	FeatureMax        = FeatureType(C.SENSORS_FEATURE_MAX)
	FeatureUnknown    = FeatureType(C.SENSORS_FEATURE_UNKNOWN)
)

const (
	SubfeatureInInput              = SubfeatureType(C.SENSORS_SUBFEATURE_IN_INPUT)
	SubfeatureInMin                = SubfeatureType(C.SENSORS_SUBFEATURE_IN_MIN)
	SubfeatureInMax                = SubfeatureType(C.SENSORS_SUBFEATURE_IN_MAX)
	SubfeatureInLcrit              = SubfeatureType(C.SENSORS_SUBFEATURE_IN_LCRIT)
	SubfeatureInCrit               = SubfeatureType(C.SENSORS_SUBFEATURE_IN_CRIT)
	SubfeatureInAverage            = SubfeatureType(C.SENSORS_SUBFEATURE_IN_AVERAGE)
	SubfeatureInLowest             = SubfeatureType(C.SENSORS_SUBFEATURE_IN_LOWEST)
	SubfeatureInHighest            = SubfeatureType(C.SENSORS_SUBFEATURE_IN_HIGHEST)
	SubfeatureInAlarm              = SubfeatureType(C.SENSORS_SUBFEATURE_IN_ALARM)
	SubfeatureInMinAlarm           = SubfeatureType(C.SENSORS_SUBFEATURE_IN_MIN_ALARM)
	SubfeatureInMaxAlarm           = SubfeatureType(C.SENSORS_SUBFEATURE_IN_MAX_ALARM)
	SubfeatureInBeep               = SubfeatureType(C.SENSORS_SUBFEATURE_IN_BEEP)
	SubfeatureInLcritAlarm         = SubfeatureType(C.SENSORS_SUBFEATURE_IN_LCRIT_ALARM)
	SubfeatureInCritAlarm          = SubfeatureType(C.SENSORS_SUBFEATURE_IN_CRIT_ALARM)
	SubfeatureFanInput             = SubfeatureType(C.SENSORS_SUBFEATURE_FAN_INPUT)
	SubfeatureFanMin               = SubfeatureType(C.SENSORS_SUBFEATURE_FAN_MIN)
	SubfeatureFanMax               = SubfeatureType(C.SENSORS_SUBFEATURE_FAN_MAX)
	SubfeatureFanAlarm             = SubfeatureType(C.SENSORS_SUBFEATURE_FAN_ALARM)
	SubfeatureFanFault             = SubfeatureType(C.SENSORS_SUBFEATURE_FAN_FAULT)
	SubfeatureFanDiv               = SubfeatureType(C.SENSORS_SUBFEATURE_FAN_DIV)
	SubfeatureFanBeep              = SubfeatureType(C.SENSORS_SUBFEATURE_FAN_BEEP)
	SubfeatureFanPulses            = SubfeatureType(C.SENSORS_SUBFEATURE_FAN_PULSES)
	SubfeatureFanMinAlarm          = SubfeatureType(C.SENSORS_SUBFEATURE_FAN_MIN_ALARM)
	SubfeatureFanMaxAlarm          = SubfeatureType(C.SENSORS_SUBFEATURE_FAN_MAX_ALARM)
	SubfeatureTempInput            = SubfeatureType(C.SENSORS_SUBFEATURE_TEMP_INPUT)
	SubfeatureTempMax              = SubfeatureType(C.SENSORS_SUBFEATURE_TEMP_MAX)
	SubfeatureTempMaxHyst          = SubfeatureType(C.SENSORS_SUBFEATURE_TEMP_MAX_HYST)
	SubfeatureTempMin              = SubfeatureType(C.SENSORS_SUBFEATURE_TEMP_MIN)
	SubfeatureTempCrit             = SubfeatureType(C.SENSORS_SUBFEATURE_TEMP_CRIT)
	SubfeatureTempCritHyst         = SubfeatureType(C.SENSORS_SUBFEATURE_TEMP_CRIT_HYST)
	SubfeatureTempLcrit            = SubfeatureType(C.SENSORS_SUBFEATURE_TEMP_LCRIT)
	SubfeatureTempEmergency        = SubfeatureType(C.SENSORS_SUBFEATURE_TEMP_EMERGENCY)
	SubfeatureTempEmergencyHyst    = SubfeatureType(C.SENSORS_SUBFEATURE_TEMP_EMERGENCY_HYST)
	SubfeatureTempLowest           = SubfeatureType(C.SENSORS_SUBFEATURE_TEMP_LOWEST)
	SubfeatureTempHighest          = SubfeatureType(C.SENSORS_SUBFEATURE_TEMP_HIGHEST)
	SubfeatureTempMinHyst          = SubfeatureType(C.SENSORS_SUBFEATURE_TEMP_MIN_HYST)
	SubfeatureTempLcritHyst        = SubfeatureType(C.SENSORS_SUBFEATURE_TEMP_LCRIT_HYST)
	SubfeatureTempAlarm            = SubfeatureType(C.SENSORS_SUBFEATURE_TEMP_ALARM)
	SubfeatureTempMaxAlarm         = SubfeatureType(C.SENSORS_SUBFEATURE_TEMP_MAX_ALARM)
	SubfeatureTempMinAlarm         = SubfeatureType(C.SENSORS_SUBFEATURE_TEMP_MIN_ALARM)
	SubfeatureTempCritAlarm        = SubfeatureType(C.SENSORS_SUBFEATURE_TEMP_CRIT_ALARM)
	SubfeatureTempFault            = SubfeatureType(C.SENSORS_SUBFEATURE_TEMP_FAULT)
	SubfeatureTempType             = SubfeatureType(C.SENSORS_SUBFEATURE_TEMP_TYPE)
	SubfeatureTempOffset           = SubfeatureType(C.SENSORS_SUBFEATURE_TEMP_OFFSET)
	SubfeatureTempBeep             = SubfeatureType(C.SENSORS_SUBFEATURE_TEMP_BEEP)
	SubfeatureTempEmergencyAlarm   = SubfeatureType(C.SENSORS_SUBFEATURE_TEMP_EMERGENCY_ALARM)
	SubfeatureTempLcritAlarm       = SubfeatureType(C.SENSORS_SUBFEATURE_TEMP_LCRIT_ALARM)
	SubfeaturePowerAverage         = SubfeatureType(C.SENSORS_SUBFEATURE_POWER_AVERAGE)
	SubfeaturePowerAverageHighest  = SubfeatureType(C.SENSORS_SUBFEATURE_POWER_AVERAGE_HIGHEST)
	SubfeaturePowerAverageLowest   = SubfeatureType(C.SENSORS_SUBFEATURE_POWER_AVERAGE_LOWEST)
	SubfeaturePowerInput           = SubfeatureType(C.SENSORS_SUBFEATURE_POWER_INPUT)
	SubfeaturePowerInputHighest    = SubfeatureType(C.SENSORS_SUBFEATURE_POWER_INPUT_HIGHEST)
	SubfeaturePowerInputLowest     = SubfeatureType(C.SENSORS_SUBFEATURE_POWER_INPUT_LOWEST)
	SubfeaturePowerCap             = SubfeatureType(C.SENSORS_SUBFEATURE_POWER_CAP)
	SubfeaturePowerCapHyst         = SubfeatureType(C.SENSORS_SUBFEATURE_POWER_CAP_HYST)
	SubfeaturePowerMax             = SubfeatureType(C.SENSORS_SUBFEATURE_POWER_MAX)
	SubfeaturePowerCrit            = SubfeatureType(C.SENSORS_SUBFEATURE_POWER_CRIT)
	SubfeaturePowerAverageInterval = SubfeatureType(C.SENSORS_SUBFEATURE_POWER_AVERAGE_INTERVAL)
	SubfeaturePowerAlarm           = SubfeatureType(C.SENSORS_SUBFEATURE_POWER_ALARM)
	SubfeaturePowerCapAlarm        = SubfeatureType(C.SENSORS_SUBFEATURE_POWER_CAP_ALARM)
	SubfeaturePowerMaxAlarm        = SubfeatureType(C.SENSORS_SUBFEATURE_POWER_MAX_ALARM)
	SubfeaturePowerCritAlarm       = SubfeatureType(C.SENSORS_SUBFEATURE_POWER_CRIT_ALARM)
	SubfeatureEnergyInput          = SubfeatureType(C.SENSORS_SUBFEATURE_ENERGY_INPUT)
	SubfeatureCurrInput            = SubfeatureType(C.SENSORS_SUBFEATURE_CURR_INPUT)
	SubfeatureCurrMin              = SubfeatureType(C.SENSORS_SUBFEATURE_CURR_MIN)
	SubfeatureCurrMax              = SubfeatureType(C.SENSORS_SUBFEATURE_CURR_MAX)
	SubfeatureCurrLcrit            = SubfeatureType(C.SENSORS_SUBFEATURE_CURR_LCRIT)
	SubfeatureCurrCrit             = SubfeatureType(C.SENSORS_SUBFEATURE_CURR_CRIT)
	SubfeatureCurrAverage          = SubfeatureType(C.SENSORS_SUBFEATURE_CURR_AVERAGE)
	SubfeatureCurrLowest           = SubfeatureType(C.SENSORS_SUBFEATURE_CURR_LOWEST)
	SubfeatureCurrHighest          = SubfeatureType(C.SENSORS_SUBFEATURE_CURR_HIGHEST)
	SubfeatureCurrAlarm            = SubfeatureType(C.SENSORS_SUBFEATURE_CURR_ALARM)
	SubfeatureCurrMinAlarm         = SubfeatureType(C.SENSORS_SUBFEATURE_CURR_MIN_ALARM)
	SubfeatureCurrMaxAlarm         = SubfeatureType(C.SENSORS_SUBFEATURE_CURR_MAX_ALARM)
	SubfeatureCurrBeep             = SubfeatureType(C.SENSORS_SUBFEATURE_CURR_BEEP)
	SubfeatureCurrLcritAlarm       = SubfeatureType(C.SENSORS_SUBFEATURE_CURR_LCRIT_ALARM)
	SubfeatureCurrCritAlarm        = SubfeatureType(C.SENSORS_SUBFEATURE_CURR_CRIT_ALARM)
	SubfeatureHumidityInput        = SubfeatureType(C.SENSORS_SUBFEATURE_HUMIDITY_INPUT)
	SubfeatureVid                  = SubfeatureType(C.SENSORS_SUBFEATURE_VID)
	SubfeatureIntrusionAlarm       = SubfeatureType(C.SENSORS_SUBFEATURE_INTRUSION_ALARM)
	SubfeatureIntrusionBeep        = SubfeatureType(C.SENSORS_SUBFEATURE_INTRUSION_BEEP)
	SubfeatureBeepEnable           = SubfeatureType(C.SENSORS_SUBFEATURE_BEEP_ENABLE)
	SubfeatureUnknown              = SubfeatureType(C.SENSORS_SUBFEATURE_UNKNOWN)
)
